version: '3.3'
services:
  db:
    build:
      context: db
      dockerfile: ./deploy/Dockerfile
    image: db
    volumes:
    - db_data:/data
  server:
    build:
      context: server
      dockerfile: ./deploy/Dockerfile
    environment:
      - DB_URL=mongodb://db:27017/gameroom
    image: server
    depends_on:
      - db
    ports:
    - "8080:8080"
  realtime:
    build:
      context: realtime
      dockerfile: ./deploy/Dockerfile
    environment:
      - SOCKET_SERVER_PORT=9000
    image: realtime
    depends_on:
      - server
    ports:
    - "9000:9000"
  client:
    build:
      context: client
      dockerfile: ./deploy/Dockerfile
    image: client
    depends_on:
      - server
    ports:
    - "8082:80"

volumes:
  db_data: {}